name: "Build and Deploy: Develop"
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}


on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches: [develop]

permissions:
  contents: write
  packages: write
  actions: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_ROOT: ghcr.io/ahs-tech

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Failed step
      #   run: ls nonexisten/
      
      - run: echo ${GITHUB_RUN_NUMBER}
        name: Pring github run number
      - name: get job status
        if: always()
        run: echo ${{ job.status }}

  deploy:
    # if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          # Fetch all history to ensure latest commit is accessible
          fetch-depth: 0
          # Check out the main branch for pull requests, otherwise use the current ref
          # ref: ${{ github.event_name == 'pull_request' && 'develop' || github.head_ref || github.ref_name }}
      - name: Print github context json
        run: echo "${{ toJson(github) }}"
      - name: Print vars context json
        run: echo "${{ toJson(vars) }}"
      - name: Print env context json
        run: echo "${{ toJson(env) }}"
      - name: Print env variables
        run: printenv

  slack-notification:
    if: always()
    name: Slack Notification
    needs: [build, deploy]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get results from previous jobs
        id: get-results
        run: |
          echo "BUILD_RESULT: ${{ needs.build.result }}"
          echo "DEPLOY_RESULT: ${{ needs.deploy.result }}"

      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: general
          SLACK_USERNAME: GitHub Actions
          # SLACK_ICON_EMOJI: ':ghactions:'
          SLACK_COLOR: ${{ (needs.build.result == 'success' && needs.deploy.result == 'success') && 'success' || 'failure' }}
          SLACK_MESSAGE: ":hammer_and_wrench: Triggered by ${{ github.actor }}"
          SLACK_TITLE: "Pipeline Status: ${{ github.repository }}"

      - name: Write the review
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            text: "Danny Torrence left a 1 star review for your property."
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Danny Torrence left the following review for your property:"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "<https://example.com|*Overlook Hotel*> :star: \n Doors had too many axe holes, guest in room 237 was far too rowdy, whole place felt stuck in the 1920s."
                accessory:
                  type: "image"
                  image_url: "https://is5-ssl.mzstatic.com/image/thumb/Purple3/v4/d3/72/5c/d3725c8f-c642-5d69-1904-aa36e4297885/source/256x256bb.jpg"
                  alt_text: "Haunted hotel image"
              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*Average Rating*: 1.0"
                  - type: "mrkdwn"
                    text: "*Review Count*: 256"

      - name: Get current branch
        run: git branch --show-current

