name: "Build and Deploy: Develop"
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}


on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches: [develop]

permissions:
  contents: write
  packages: write
  actions: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_ROOT: ghcr.io/ahs-tech

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: ls nonexisten/
      - name: get job status
        if: always()
        run: echo ${{ job.status }}

  deploy:
    # if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          # Fetch all history to ensure latest commit is accessible
          fetch-depth: 0
          # Check out the main branch for pull requests, otherwise use the current ref
          # ref: ${{ github.event_name == 'pull_request' && 'develop' || github.head_ref || github.ref_name }}
      - name: Print github context json
        run: echo "${{ toJson(github) }}"

      - name: Print env variables
        run: printenv

  slack-notification:
    if: always()
    name: Slack Notification
    needs: [build, deploy]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: general
          SLACK_USERNAME: GitHub Actions
          # SLACK_ICON_EMOJI: ':ghactions:'
          SLACK_COLOR: ${{ needs.build.result	 }}
          SLACK_MESSAGE: ":hammer_and_wrench: Triggered by ${{ github.actor }}"
          SLACK_TITLE: "Pipeline Status: ${{ github.repository }}"

      - name: Get current branch
        run: git branch --show-current

